// Code generated by mockery v1.0.0. DO NOT EDIT.

package ihash_mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Hash provides a mock function with given fields: word
func (_m *Service) Hash(word string) (string, error) {
	ret := _m.Called(word)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(word)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(word)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Match provides a mock function with given fields: hashedWord, plainWord
func (_m *Service) Match(hashedWord string, plainWord string) (bool, error) {
	ret := _m.Called(hashedWord, plainWord)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hashedWord, plainWord)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hashedWord, plainWord)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
